/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { LocationSegments, RouterHistory } from "@stencil/router";
import { NotificationSeverity } from "services/notifications";
export namespace Components {
    interface AppRoot {
        "history": RouterHistory;
        "location": LocationSegments;
    }
    interface NumContainerAuthenticate {
    }
    interface NumContainerWelcome {
    }
    interface NumNotification {
        "action": () => void;
        "actionKey": string;
        "close": () => void;
        "messageKey": string;
        "messageOptions"?: { [key: string]: any };
        "severity": NotificationSeverity;
    }
    interface NumNotifications {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLNumContainerAuthenticateElement extends Components.NumContainerAuthenticate, HTMLStencilElement {
    }
    var HTMLNumContainerAuthenticateElement: {
        prototype: HTMLNumContainerAuthenticateElement;
        new (): HTMLNumContainerAuthenticateElement;
    };
    interface HTMLNumContainerWelcomeElement extends Components.NumContainerWelcome, HTMLStencilElement {
    }
    var HTMLNumContainerWelcomeElement: {
        prototype: HTMLNumContainerWelcomeElement;
        new (): HTMLNumContainerWelcomeElement;
    };
    interface HTMLNumNotificationElement extends Components.NumNotification, HTMLStencilElement {
    }
    var HTMLNumNotificationElement: {
        prototype: HTMLNumNotificationElement;
        new (): HTMLNumNotificationElement;
    };
    interface HTMLNumNotificationsElement extends Components.NumNotifications, HTMLStencilElement {
    }
    var HTMLNumNotificationsElement: {
        prototype: HTMLNumNotificationsElement;
        new (): HTMLNumNotificationsElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "num-container-authenticate": HTMLNumContainerAuthenticateElement;
        "num-container-welcome": HTMLNumContainerWelcomeElement;
        "num-notification": HTMLNumNotificationElement;
        "num-notifications": HTMLNumNotificationsElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
        "history"?: RouterHistory;
        "location"?: LocationSegments;
    }
    interface NumContainerAuthenticate {
    }
    interface NumContainerWelcome {
    }
    interface NumNotification {
        "action"?: () => void;
        "actionKey": string;
        "close": () => void;
        "messageKey": string;
        "messageOptions"?: { [key: string]: any };
        "severity": NotificationSeverity;
    }
    interface NumNotifications {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "num-container-authenticate": NumContainerAuthenticate;
        "num-container-welcome": NumContainerWelcome;
        "num-notification": NumNotification;
        "num-notifications": NumNotifications;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "num-container-authenticate": LocalJSX.NumContainerAuthenticate & JSXBase.HTMLAttributes<HTMLNumContainerAuthenticateElement>;
            "num-container-welcome": LocalJSX.NumContainerWelcome & JSXBase.HTMLAttributes<HTMLNumContainerWelcomeElement>;
            "num-notification": LocalJSX.NumNotification & JSXBase.HTMLAttributes<HTMLNumNotificationElement>;
            "num-notifications": LocalJSX.NumNotifications & JSXBase.HTMLAttributes<HTMLNumNotificationsElement>;
        }
    }
}
